type Purpose = enum {
  P0,
  P1,
  P2,
  P3,
  P4,
  P5,
  P6,
  P7,
};

type TimeToPay = enum {
  T0,
  T1,
  T2,
  T3,
};

type CreditRequestEvent = enum {
  Success,
  CollateralTooLow,
};

type IoCreditRequestState = struct {
  all_requests: vec struct { actor_id, struct { u32, u32, Purpose, TimeToPay } },
};

constructor {
  New : ();
};

service CreditRequest {
  RequestCredit : (amount_requested: u32, collateral: u32, purpose: Purpose, time_to_pay: TimeToPay) -> CreditRequestEvent;
  query GetRequests : () -> IoCreditRequestState;
};

